name: run-script
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout Repo

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Download the Model PKL
      run: |
        az extension add -n azure-cli-ml
        az ml model download -i portodrivermodel:1 --resource-group szgroup --workspace-name szmlworkspace -t app
      shell: bash

    - uses: azure/docker-login@v1
      with:
        login-server: szmlcr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # - name: Build the tagged Docker image
    #   run: |
    #     docker build . --file Dockerfile --tag mlops:latest

    - run: |
        docker build . -t szmlcr.azurecr.io/mlops-inference:${{ github.sha }}
        docker push szmlcr.azurecr.io/mlops-inference:${{ github.sha }}