name: run-script
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout Repo

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: ls before
      run: |
        pwd
        ls
        tree
      shell: bash

    - name: Download the Model PKL
      run: |
        az extension add -n azure-cli-ml
        az ml model download -i portodrivermodel:1 --resource-group szgroup --workspace-name szmlworkspace -t .
      shell: bash

    - name: ls after
      run: |
        pwd
        ls
        tree
      shell: bash

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build image and push to GitHub Container Registry
      run: |
        docker build . -t ghcr.io/shinojedakkara/mlops-inference-service:${{ github.run_number }}
        docker push ghcr.io/shinojedakkara/mlops-inference-service:${{ github.run_number }}
