name: run-script
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout Repo

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Download the Model PKL
      run: |
        az extension add -n azure-cli-ml
        az ml model download -i portodrivermodel:1 --resource-group szgroup --workspace-name szmlworkspace -t .
        pwd
      shell: bash

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: retaildevcrews
        password: ${{ secrets.GHCR_PAT }}

    - name: Build image and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        tags: |
          ghcr.io/retaildevcrews/mlops-inference-service:${{ github.run_attempt }}
        context: .
        push: true
